name: Build and release
run-name: ${{ github.actor }} is releasing the newest version.
on:
  push:
    branches: [main]
jobs:
  build-and-release:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - run: java --version

      - name: Build with Maven
        run: |
          chmod +x ./cicd/build.sh
          ./cicd/build.sh

      - name: Release build
        run: |
          a=$(date +"%Y-%m-%d")-${{ github.sha }}
          ls ./dist/
          gh release create $a --title "franklyn $a" --generate-notes ./dist/*.jar
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
