name: Build and release
run-name: ${{ github.actor }} is releasing the newest version.
on:
  push:
    branches: [main]
jobs:
  build-and-release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - run: java --version

      - name: Build with Maven
        run: |
          chmod +x ./cicd/build.sh
          ./cicd/build.sh

      - run: |
          git pull --unshallow
          git log $(git describe --tags --abbrev=0)..HEAD | git shortlog > release-notes.txt
          cat release-notes.txt

      - name: Release the build
        run: |
          tag="$(date +"%Y.%m.%d")-(git rev-parse --short HEAD)"
          gh release create $tag ./dist/*-runner --title "franklyn $tag" --notes-file release-notes.txt --prerelease
          git tag --sort=refname
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
